# kf-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfc1-vnf1
  labels:
    app: sfc1-vnf1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfc1-vnf1
  template:
    metadata:
      labels:
        app: sfc1-vnf1
    spec:
      containers:
        - name: sfc1-vnf1
          image: sfc1-vnf1:v1
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: sfc1-vnf1-service
spec:
  selector:
    app: sfc1-vnf1
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

